### ISSUE TITLE
 could not determine kind of name for C.rocksdb_backup_engine_create_new_backup_flush

### ISSUE THREAD

**Issue by arlottang** [tecbot/gorocksdb#200]
go run test.go 

# github.com/tecbot/gorocksdb
../../pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/backup.go:112:2: could not determine kind of name for C.rocksdb_backup_engine_create_new_backup_flush

I'm using the latest version，rocksdb master， Why is this problem？

**Comment by arlottang** [comment]
This problem has been solved

**Comment by collinmsn** [comment]
> This problem has been solved

how did you solved this problem?

**Comment by LikeTheWindGone** [comment]
I'm stuck here too, could you show more details about how to solve that?
