### ISSUE TITLE
slice transform seek inconsistent after db reopen?

### ISSUE THREAD

**Issue by yinhm** [tecbot/gorocksdb#24]
This has been bugs me several days,  in TestCustomSliceTransform[1], if I open the old database without Destroy it first, then do the same iteration(without Put changes), the tests fails.

The docs[2] says: "If there is one or more keys in the database matching prefix of lookup_key, RocksDB will place the iterator to the key equal or **larger than lookup_key** of the same prefix, as for total ordering mode."

I'm not sure is this the expect behavior, it so, how do we do SeekToLast(), isn't this make SeekToLast() useless. 

```
$go test -run TestCustomSliceTransform
...........x
Failures:


  * /home/yinhm/gopath/src/github.com/yinhm/gorocksdb/slice_transform_test.go 
  Line 100:
  Expected: '3'
  Actual:   '6'
  (Should be equal)


12 assertions thus far
```

[1] https://github.com/yinhm/gorocksdb/commit/db9e6ddd99916eeb6fff5372f9a2c404e85b1db2
[2] https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes

**Comment by yinhm** [comment]
I should mention that I'm using Ubuntu 64bit with go v1.4.2, rocksdb 3.9.1-1.

**Comment by rdallman** [comment]
Hi @yinhm that's a good question that is not documented very well in either rocksdb or leveldb as far as I can tell. That is the expected behavior. I cannot find the thread now but the easiest thing to do is to make `SeekToLast` work is to make a definitive last key that is at least the length of your prefix transform [if you are using the fixed size slice transform]. The way to do this is upon opening the db to insert a value like so:

```c
// sizeof(last_key) as shown is 16, lengthen as needed.
char last_key[] = { 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF };
char last_val[] = { };
db.Put(wo, last_key, last_val);
```

if you are using column families, you will have to do this for each column family that you have opened. now you should be able to do `SeekToLast()` and not invalidate the iterator, just `it.Prev()` once and you have your actual last key (or invalid iterator if your range was empty). does that answer your question?

**Comment by yinhm** [comment]
@rdallman  thanks for the tip, unfortunately I didn't managed get it work as what I want.

Convey section [1], section [2] result fail tests, section[3] was SeekToLast result **virtual void rocksdb::PlainTableIterator::SeekToLast(): Assertion `false' failed.**


``
$ go test -run TestFixedPrefixTransformWithMax
........x.x
Failures:

  * /home/yinhm/gopath/src/github.com/yinhm/gorocksdb/slice_transform_test.go 
  Line 221:
  Expected: '3'
  Actual:   '7'
  (Should be equal)

  * /home/yinhm/gopath/src/github.com/yinhm/gorocksdb/slice_transform_test.go 
  Line 238:
  Expected: '3'
  Actual:   '7'
  (Should be equal)


11 assertions thus far

--- FAIL: TestFixedPrefixTransformWithMax (0.02s)
```

```
$ go test -run TestFixedPrefixTransformWithMax
........x.xgorocksdb.test: table/plain_table_reader.cc:625: virtual void rocksdb::PlainTableIterator::SeekToLast(): Assertion `false' failed.
SIGABRT: abort
PC=0x7f32185d3cc9
signal arrived during cgo execution

goroutine 5 [syscall, locked to thread]:
runtime.cgocall_errno(0x409700, 0xc208097b28, 0xc200000000)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208097b08 sp=0xc208097ae0
github.com/yinhm/gorocksdb._Cfunc_rocksdb_iter_seek_to_last(0x1c5ce10)
	github.com/yinhm/gorocksdb/_test/_obj_test/_cgo_gotypes.go:436 +0x45 fp=0xc208097b28 sp=0xc208097b08
github.com/yinhm/gorocksdb.(*Iterator).SeekToLast(0xc208044078)
	/home/yinhm/gopath/src/github.com/yinhm/gorocksdb/iterator.go:90 +0x2b fp=0xc208097b38 sp=0xc208097b28
github.com/yinhm/gorocksdb.func·026()
	/home/yinhm/gopath/src/github.com/yinhm/gorocksdb/slice_transform_test.go:252 +0xe1 fp=0xc208097bc8 sp=0xc208097b38
github.com/smartystreets/goconvey/convey.(*action).Invoke(0xc20803cc60)
......
```

[1] [2] [3] https://github.com/yinhm/gorocksdb/commit/f90f8600b28466da6fa4b1aa37c7f6cae9bcb129

**Comment by yinhm** [comment]
It is really weird, I didn't trigger any rocksdb assertion failure yesterday when I use SeekToLast, just did not get what I want.

I think I may just wrote a reverse index directly to get what I want since I on a really  tight schedule(Disclosure: I working on a friendfeed clone which will open source later, and friendfeed is closing, real soon...)

Please help, Many thanks.

**Comment by yinhm** [comment]
Regarding to the previous ** virtual void rocksdb::PlainTableIterator::SeekToLast(): Assertion `false' failed.**, I was wrong, I miss used the table format, rocksdb wiki indicated[1] PlainTable dot not support iter->Prev() seek, changed to SetBlockBasedTableFactory resolved this issue.

But the fail tests remain the same.

[1] https://github.com/facebook/rocksdb/wiki/PlainTable-Format

**Comment by yinhm** [comment]
thanks @rdallman, I think using 0xFF to padding key for each prefix should solve my problem: backward seek, tests snippet are here:

```
		Convey("0xFF MAX DELIMITER: match prefix[0xFF...]", func() {
			ro := NewDefaultReadOptions()
			it := rdb.NewIterator(ro)
			defer it.Close()
			numFound := 0

			it.Seek(maxBarKey)
			it.Prev()
			for ; it.ValidForPrefix([]byte("bar")); it.Prev() {
				key := it.Key()
				defer key.Free()
				log.Println("Found key:", string(key.Data()))
				numFound++
			}
			So(it.Err(), ShouldBeNil)
			So(numFound, ShouldEqual, 3)
		})
```

The inconsistent if we are using Plain table as TestCustomSliceTransform test shows, so I'll leave this issue open.

**Comment by tristanz** [comment]
What is the default table format for gorocksdb?  BlockBasedTable or PlainTable?

**Comment by tristanz** [comment]
Just for posterity, I also was seeing inconsistent seek behavior with `it.Prev()` caused by seeking past the end of the database.  @rdallman's  solution worked, by creating a definitive last key when creating the database:

```
db.Put(wo, []byte{0xFF}, []byte{})
```
