### ISSUE TITLE
reusing []byte in MergeOperator

### ISSUE THREAD

**Issue by mschoch** [tecbot/gorocksdb#26]
In my use case, all values have a fixed size.  I'm wondering if I can safely reuse the []byte in the following cases:
1.  In PartialMerge, store result in leftOperand and return that, avoiding allocating additional bytes.
2.  In FullMerge, store result in existingValue and return that.

I've reviewed the code, but the use of unsafe.Pointer makes me doubt most of what I know on the subject.  I've tested it and it seems to work, but wonder if I'm just getting lucky and will face a crash down the road.

**Comment by rdallman** [comment]
Hi Marty. I've had really bad luck using the gorocksdb MergeOperator and friends even with allocating my own slices in each of PartialMerge and FullMerge. In a lot of cases I've seen the merges complete and have the desired values (println style) but when you Get() the same key it won't return that value (in a lot of cases, I'm getting a nil slice back). I'd recommend writing them in c++ and hooking them up -- as a bonus, it's a nice little speed bump.
