### ISSUE TITLE
Support for getting memory usage info

### ISSUE THREAD

**Issue by ashwin95r** [tecbot/gorocksdb#54]
This is related to the post : https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB

Currently, gorocksdb supports getting "Memtable" and "Index and filter blocks" size but not "block cache" and "blocks pinned by iterators". In order to get total memory used by RocksDB, all four values are needed. Is there any other way to get total memory usage by RocksDB or should there be support for GetPinnedUsage() and GetUsage()?

Thanks.

**Comment by vitalyisaev2** [comment]
`GetPinnedUsage()` and `GetUsage()` are supported now: https://godoc.org/github.com/tecbot/gorocksdb#Cache.GetPinnedUsage

**Comment by jamesbibby** [comment]
All of these are implemented as far as I can tell, closing
