### ISSUE TITLE
Go get fails for embedded version

### ISSUE THREAD

**Issue by pawanrawal** [tecbot/gorocksdb#57]
My understanding here is that if I want to install the embedded version of gorocksdb, I don't need to have RocksDB installed on my machine.

Though `go get -tags=embed github.com/tecbot/gorocksdb` fails with the error.

```
# github.com/tecbot/gorocksdb
src/github.com/tecbot/gorocksdb/options.go:328: not enough arguments in call to _Cfunc_rocksdb_options_set_compression_options
```

Anything that I might be doing wrong here? My g++ version is 4.8.4.

**Comment by jrots** [comment]
got the same error, changing     
the code in src/github.com/tecbot/gorocksdb/options.go:328, from
` C.rocksdb_options_set_compression_options(opts.c, C.int(value.WindowBits), C.int(value.Level), C.int(value.Strategy))`
to :
`C.rocksdb_options_set_compression_options(opts.c, C.int(value.WindowBits), C.int(value.Level), C.int(value.Strategy), C.int(0))`
worked for me
