### ISSUE TITLE
Slice.Free()?

### ISSUE THREAD

**Issue by rubenv** [tecbot/gorocksdb#59]
There's a `Free()` method on `Slice`.

There's little mention on this in the documentation, so I'm left wondering as to when/whether I should use it.

Intuitively I'd expect it to free the underlying resources in the native library.

Thus:

* If I don't call `Free()`, will this cause a memory leak?
* When is it safe to call `Free()`?
* There's this code:

```go
func (iter *Iterator) ValidForPrefix(prefix []byte) bool {
	return C.rocksdb_iter_valid(iter.c) != 0 && bytes.HasPrefix(iter.Key().Data(), prefix)
}
```

The result of `iter.Key()` is a `*Slice`, which is used but never freed here. Does that have a leak?

**Comment by icholy** [comment]
AFAIK you don't have to call it, but the byte slice returned from `Slice.Data` will not be valid on the next iteration.

**Comment by rubenv** [comment]
@icholy @tecbot I might be wrong, but my testing does seem to indicate a gradually increasing memory leak. Fixing {{ValidForPrefix()}} seems to get rid of it. Pull request in #60.

**Comment by rubenv** [comment]
Correction: #65.
